### PR TITLE
Upgraded to Flow 0.54

### LINKED ISSUE #3345: Update flow definitions for 0.53 format
### **bug report** 

With the updated version of Flow (0.53), the React definitions have changed : https://github.com/facebook/flow/releases/tag/v0.53.0

### What is the current behavior?
When using the package's definition it now fails

### What is the expected behavior?
It wouldn't fail on redux-forms definitions

### Other information
I assume you should maybe release a new version with updated flow defs. Check out https://www.npmjs.com/package/flow-upgrade as is can automate some of the update

### PR DESCRIPTION
**Pull request by erikras**
🎉 W00t!  🎉

Fixes #3345.

### CODE REVIEW

**Comment by erikras** [comment]
Oops. https://github.com/facebook/flow/issues/4801 😢

**Comment by chirag04** [comment]
@erikras can you bump publish a new version on npm too? 🙏

**Comment by erikras** [comment]
Published as [`v7.0.4`](https://github.com/erikras/redux-form/releases/tag/v7.0.4).

**Comment by nsb** [comment]
Flow complains when using the latest redux form definitions

screenshot from 2017-09-06 15-27-59

**Pull request merged**
