### PR TITLE
Run lint, flow and coverage on travis

### PR DESCRIPTION
**Pull request by skovhus**
Make it clear what targets are run on CI:
- lint
- flow
- test with coverage

### CODE REVIEW

**Comment by skovhus** [comment]
Ah, `prepublish` already runs test and flow...

**Comment by erikras** [comment]
Nah, I think the `.travis.yaml` makes it clear enough.

Thanks, though.

**Comment by skovhus** [comment]
The thing is that `prepublish` currently runs:
- npm run test 
- npm run test:flow 

Travis runs
- npm run lint
 - npm test
 - npm run test:cov
 - npm run test:codecov

(so test is running 3 times currently on CI...).

### Proposal

Would make more sense (and speed up travis a lot up) if `prepublish` ran:

The thing is that `prepublish` ran:
- npm run lint
- npm run test:flow 
- npm run test:cov

And Travis additional step ran
 - npm run test:codecov

**Comment by erikras** [comment]
Dammit, you're right again.

**Comment by erikras** [comment]
Why can't I reopen this PR, Github??

**Comment by skovhus** [comment]
https://github.com/erikras/redux-form/pull/3470

**Pull request closed without merging**
