### PR TITLE
fix of the uncaught exception in promise within asyncValidation

### PR DESCRIPTION
**Pull request by Roman-Maksimov**

### CODE REVIEW

**Comment by gustavohenke** [comment]
Can you prove this?

**Comment by Roman-Maksimov** [comment]
Read the issue https://github.com/erikras/redux-form/issues/1297, please. It's status is `closed`, but the problem still exists.

**Comment by Roman-Maksimov** [comment]
About test case, the asyn validation is not covered within `src/__tests__/Form.spec.js` at all. It might be too coprehensive issue. I think, it will be better to implement the test cases by authors of the project.

**Comment by gustavohenke** [comment]
Can you confirm whether your issue is with https://github.com/erikras/redux-form/issues/1297#issuecomment-277038603?

It's the only way I found to reproduce that issue consistently.

**Comment by Roman-Maksimov** [comment]
Yep. Exactly. This is the case.
If the `sync` validation is OK and `async` fails, the `uncaught promise error` from `submit` method appears.

**Comment by erikras** [comment]
Published in [`v7.0.3`](https://github.com/erikras/redux-form/releases/tag/v7.0.3).

**Comment by miracle2k** [comment]
I believe this leads to errors being swalled in other cases: https://github.com/erikras/redux-form/issues/3303

**Pull request merged**
