### PR TITLE
--DO NOT MERGE YET--

### PR DESCRIPTION
**Pull request by asaf**
Support for nested fields.

Hey,
This is far from a complete version but it exposes a new approach for handling form fields in a nested way,

see: #55 

Thoughts?

### CODE REVIEW

**Comment by erikras** [comment]
I'd like some tests for that `getSet.js`. That's the kind of function that both a) can be easily tested, and b) really needs to work 100% correct.

**Comment by erikras** [comment]
Oops, sorry about that.  I didn't see the getSet test.

**Comment by asaf** [comment]
@erikras btw u can close it for now if the (1) bothers u, it needs more work,
The question if this is a good direction or not, your call.

**Comment by erikras** [comment]
No, no, @asaf, I still think this is something to look into, and there is enough demand for it, but I haven't yet found the time to actually design a "compound" form to test its viability.

**Comment by asaf** [comment]
@erikras Look at my concept, it doesn't break anything yet provides a powerful nested form support,

The most annoying thing is that all other corresponding states to fields (touch, errors, etc) must conform the same structure... so it takes a bit time to move everything but it shouldn't be that hard.

**Comment by erikras** [comment]
Implemented.

**Pull request closed without merging**
