### PR TITLE
Small doc update registeredFields - I believe this field has changed I don't know when it changed

### PR DESCRIPTION
**Pull request by rluiten**
Just noticed it comparing documentation to a logged value.

### CODE REVIEW

**Comment by erikras** [comment]
This was semi-intentionally left undocumented, but I guess it probably should be. So thanks.

**Comment by olslash** [comment]
@erikras, is this still correct?

https://github.com/erikras/redux-form/blob/6401f982cc08c030a4440ee95d29c50865454521/src/reduxForm.js#L687

screen shot 2017-02-21 at 2 51 11 pm

**Comment by gustavohenke** [comment]
[If it's not documented, then it doesn't exist](https://medium.com/@fagnerbrack/library-internals-do-not-exist-1ff50a30e3b0).

**Comment by olslash** [comment]
The PR removed fieldList and added registeredFields -- I see fieldList but registeredFields doesn't exist as document

**Comment by gustavohenke** [comment]
> I see fieldList

You see it because, well, it does exist. But the behavior should not be relied upon, *because it's not documented*.

> registeredFields doesn't exist as documented

It's also not documented.

**Pull request merged**
