### PR TITLE
fix sync validation errors flicker on changing

### LINKED ISSUE #1819: [v6.0.2-6.0.5] Sync validation makes errors flicker on changing
Specifying a validate `reduxForm({ form: 'discovery/order', validate: validateOrder })` that always returns the same error object:
When I change the form values the error flickers in an out on every keystroke. This did not exist in 6.0.1.

Edit: Tested between versions - it first appears in 6.0.2. I'm guessing this is related to 

> Bug fix involving submission error not being cleared. #1654 #1641 Thanks, @ortex!

Probably need to separate that logic for sync errors.

### PR DESCRIPTION
**Pull request by ortex**
fix #1819 sync validation errors flicker on changing

### CODE REVIEW

**Comment by ortex** [comment]
Also, fix #1884

**Comment by c10b10** [comment]
@ortex how does this fix #1884?

**Comment by ortex** [comment]
@c10b10 
In 6.0.5 if has errors could not submitting a form.
These changes allow submit form without change if has only error (e.g. `throw new SubmissionError({ _error: 'Login failed!' })`)

**Comment by ortex** [comment]
@erikras Please, can do you add a label "Hacktoberfest"? :)
https://hacktoberfest.digitalocean.com/

**Comment by erikras** [comment]
@ortex to what?

**Comment by ortex** [comment]
@erikras to this issue #1819.

**Comment by erikras** [comment]
@ortex Done. 👍

**Comment by ortex** [comment]
@erikras Thank you.

**Comment by erikras** [comment]
Published in [`v6.1.0`](https://github.com/erikras/redux-form/releases/tag/v6.1.0).

**Pull request merged**
