### PR TITLE
feat: export ReduxFormContext

### LINKED ISSUE #3852: Consider _reduxForm context part of public, semantic-versioned API
### Are you submitting a **bug report** or a **feature request**?

Feature request

Sometimes I find it way more convenient to use `_reduxForm` context directly than to use the various utility HOCs provided by redux form.  As an example, below is a container for a group of form fields I made to be embedded within other forms.  When the user types in a different tag, it fetches the metadata for that tag from graphql and then updates the other corresponding fields with the metadata accordingly.

The only problem with this is I assume it's not safe from minor or patch releases changing the structure of context.  But I think this is convenient enough that I would like to request that any such breaking changes to context only be included in a major release.

Note especially that I'm using the `sectionPrefix` field from context, which there doesn't really seem to be a way to access directly.

To do this without using context, I could pass in the form's `change` method and a prefix for field changes manually, which would not be so slick.  Perhaps I could nest `MetadataItemFieldsContainer` and its `Fields` inside of a `Field` with the same name as my section prefix, but I doubt that would completely work (and I don't think `onChange` can be used to dispatch subfield changes anyway).

```js
// @flow

import * as React from 'react'
import PropTypes from 'prop-types'
import {compose} from 'redux'
import {formValues} from 'redux-form'
import gql from 'graphql-tag'
import {graphql} from 'react-apollo'
import type {MetadataItem} from '../types/MetadataItem'
import MetadataItemFields from './MetadataItemFields'

export type Props = {
  tag: ?string,
  data: {
    metadataItem?: MetadataItem,
    loading: boolean,
  },
}

const metadataItemQuery = gql(`query MetadataItem($tag: String!) {
  metadataItem: MetadataItem(tag: $tag) {
    _id
    tag
    name
    dataType
    ... on NumericMetadataItem {
      min
      max
      units
      storagePrecision
      displayPrecision
    }
    ... on DigitalMetadataItem {
      isDigital
    }
  }
}`)

type Context = {
  _reduxForm: {
    sectionPrefix?: ?string,
    change: (field: string, newValue: any) => any,
    dispatch: (action: any) => any,
  },
}

class MetadataItemFieldsContainer extends React.Component<Props> {
  static contextTypes = {
    _reduxForm: PropTypes.shape({
      sectionPrefix: PropTypes.string,
      change: PropTypes.func.isRequired,
      dispatch: PropTypes.func.isRequired,
    }),
  }

  _updateFields = (metadataItem: MetadataItem, context: Context = this.context) => {
    const {_reduxForm: {sectionPrefix, change, dispatch}} = context
    for (let key in metadataItem) {
      const field = sectionPrefix ? `${sectionPrefix}.${key}` : key
      dispatch(change(field, metadataItem[key]))
    }
  }

  componentDidMount() {
    const {data: {metadataItem}} = this.props
    if (metadataItem) this._updateFields(metadataItem)
  }

  componentWillReceiveProps(nextProps: Props, nextContext: Context) {
    const prevMetadataItem = this.props.data.metadataItem
    const nextMetadataItem = nextProps.data.metadataItem
    if (nextMetadataItem && nextMetadataItem !== prevMetadataItem) {
      this._updateFields(nextMetadataItem, nextContext)
    }
  }

  render(): ?React.Node {
    const {
      tag, data, // eslint-disable-line no-unused-vars
      ...props
    } = this.props
    return <MetadataItemFields {...props} />
  }
}

export default compose(
  formValues('tag'),
  graphql(metadataItemQuery, {
    options: ({tag}: Props) => ({
      variables: {tag},
      errorPolicy: 'all',
    }),
  })
)(MetadataItemFieldsContainer)
```

### PR DESCRIPTION
**Pull request by jedwards1211**
Pretty please 🍒 

fix #3852

`react-router` allows components to access the ancestor `<Route>` props from context by using `withRouter`;  Likewise `redux-form` should allow components to access the ancestor form props from context.

I have a component that needs to know know its enclosing `sectionPrefix` and dispatch `change` multiple fields under that `sectionPrefix`, and the public API (`formValueSelector`, custom `Field` components, action creators and selectors, etc) just doesn't cut it for this use case.

### CODE REVIEW

**Comment by iamandrewluca** [comment]
CI errors are triggered by flow not finding react types. With this PR merged no errors are thrown.

https://github.com/erikras/redux-form/pull/4526
https://flow.org/en/docs/react/context/

**Comment by jedwards1211** [comment]
@renatoagds you're saying you want to get rid of the HoC and just have people use `useContext(ReduxFormContext)` or `ReduxFormContext.Consumer`, right?

**Comment by jedwards1211** [comment]
@renatoagds okay I got rid of the `withReduxForm` export

**Comment by iamandrewluca** [comment]
@renatoagds you are right. Also if we move to react hooks we can get rid of it tottaly. And who wants to use it will do something like this.
```
import { useForm } from 'redux-form'

export const withReduxForm(options) {
	return Component => props => {
		const form = useForm(options)
		return <Component {...props} _reduxForm={form} />
	}
}
```

**Comment by renatoagds** [comment]
@iamandrewluca @jedwards1211 sorry for the delay, we need one more thing before release this, we should update our docs and add this new export with usage examples, can one of you do that?

**Comment by renatoagds** [comment]
@iamandrewluca today @erikras is responsible to generate the new docs.

**Comment by renatoagds** [comment]
Published in [`v8.3.0`](https://github.com/redux-form/redux-form/releases/tag/v8.3.0).

**Pull request merged**
