### PR TITLE
When there are no registered fields, return an empty list rather than…

### LINKED ISSUE #1231: [V6] Submitting with no registered fields
I have the multistep wizard form which last step has no field, just a plain submit button. 

Let's consider the follow example:

```js
function WizardFirstStep({ handleSubmit }) {
  return (
    <form onSubmit={handleSubmit}>
      <Field name="username" component="input" type="text" />
      <Field name="password" component="input" type="password" />
    </form>
  );
}

export default reduxForm({
  form: 'wizard',
  destroyOnUnmount: false,
})(WizardFirstStep);
```

```js
function WizardSecondStep({ handleSubmit }) {
  return (
    <form onSubmit={handleSubmit}>
      <button type="submit">Submit</button>
    </form>
  );
}

export default reduxForm({
  form: 'wizard',
  destroyOnUnmount: false,
})(WizardSecondStep);
```

And also the main component which changes these steps (like in the examples).

The issues is the following: in the reducer of `UNREGISTER_FIELD` action if the there is no fields `registeredFields` property is [removed](https://github.com/erikras/redux-form/blob/v6/src/reducer.js#L239) and when you try to submit with the removed property [`ReduxForm:getFieldList()`](https://github.com/erikras/redux-form/blob/v6/src/reducer.js#L239)  method will throw an error. 

I think that you shouldn't remove the `registeredFields` property from the state and let it to be an empty array.

One workaround for this is to create a hidden field `<Field name="hidden" component="input" type="hidden" />` just to make that property not to be empty.

### PR DESCRIPTION
**Pull request by clayne11**
… trying to map over nothing

Fixes #1231

### CODE REVIEW

**Comment by ooflorent** [comment]
I think this change should be made into the store to ensure that `registeredFields` is always an array.
Iterating over it would have no cost.

**Comment by erikras** [comment]
I fixed this already. I'll add the test, though.

**Comment by ruiaraujo** [comment]
A release with that fix would be awesome, I am seeing some crashes in production related to registeredFields being undefined.

**Comment by erikras** [comment]
Published in [`v6.0.0-rc.1`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.1).

**Pull request closed without merging**
