### PR TITLE
Made SubmissionError identification more flexible

### PR DESCRIPTION
**Pull request by ah-adarlow**
I didn't add any further tests for this change, just made sure existing ones pass. I can if you think it's needed.

FYI, CHANGELOG.md says to run `npm run format` but there's no such script in the package.

### CODE REVIEW

**Comment by danielrob** [comment]
LGTM.

**Comment by anuraaga** [comment]
Ran into this today - can this PR be merged? @erikras ?  Two issues reported for it, #4162 and #4092

**Comment by Dman757** [comment]
Going to second the request for a merge

**Comment by vclav** [comment]
@erikras will you please make new release with this fix? I need it for my current project.

**Pull request merged**
