### PR TITLE
Events originating from numeric inputs should return numbers, not strings

### PR DESCRIPTION
**Pull request by whawker**

### CODE REVIEW

**Comment by erikras** [comment]
Very interesting. Thanks! I'll fix the linting error.

**Comment by whawker** [comment]
Fantastic, thanks @erikras (and thanks for this project!) When is the next release likely to happen?

**Comment by erikras** [comment]
Published as [`6.0.0-alpha-15`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.15).

**Comment by whawker** [comment]
@erikras is this change likely to be released on the v5.2.x branch? Or is it too much of a breaking change?

**Comment by whawker** [comment]
Hi @erikras, any chance this could get be released on v5? Whether that be v5.3.0 or v5.2.6 ?

**Comment by erikras** [comment]
Published in [`v5.3.0`](https://github.com/erikras/redux-form/releases/tag/v5.3.0).

**Comment by tomazy** [comment]
I'm afraid this commit makes validations of numeric fields impossible as anything that is not a valid number entered into an input will be converted to `NaN`. It's impossible to distinguish if the input is empty (`''`) or has some gibberish like "e32eee4e3". 
This breaks `isNumeric()` validator from `revalidate` library. 
It breaks `isRequired()` from the same library too, as `NaN` doesn't equal `null` nor empty string.

**Comment by erikras** [comment]
`NaN` is falsy, though. That's usually how I write my `isRequired()` functions.

The old functionality is still available if you just change your type to `"text"`.

**Comment by whawker** [comment]
Just to point out, if @tomazy is using the `v5.3.0` release, looks the the fix from #1136 isn't included on that branch. Maybe merging in that fix would help?

**Comment by tomazy** [comment]
Oh, sorry. I forgot to mention that I'm using the latest v5.3.1 release.

@erikras 
I'd rather avoid writing my own libraries for validation if I can use existing ones. 

> NaN is falsy, though. That's usually how I write my isRequired() functions.

I will get NaN for "33ee22" too - in this case I want to show a message that the input is invalid, not that it is missing. 

If there is "33ee22" in the input field I would like be able to tell the user: "'33ee22' is not a valid number" but I can't access the original input's value.

#1136  partially fixes the problem IMHO. You can't be consistent here if sometimes a value can be `''`, sometimes `NaN` and sometimes `42`

> The old functionality is still available if you just change your type to "text".

Having type "number" makes more sense in my app. It's 2016 ;)

**Comment by manubamba** [comment]
It adds a new problem that long numbers will not render correctly.

for eg: 12345678901234567 will get converted to 12345678901234568

**Pull request merged**
