### PR TITLE
Dispatch submit

### PR DESCRIPTION
**Pull request by ecnaidar**
Setting `submitAsSideEffect` flag makes `handleSubmit` function to `dispatch` result from user-provided `onSubmit` function and skips reacting to result in other ways (submission success/failure) as it is expected that the library consumer will handle these processes manually.

### CODE REVIEW

**Comment by erikras** [comment]
This looks great! 👍

Needs docs and tests to get merged.

**Comment by schleumer** [comment]
What's the current status of this merge?

**Comment by ecnaidar** [comment]
@schleumer finishing up examples for both redux observable and saga, needs docs and tests then good to go

**Comment by ecnaidar** [comment]
Should be ready to merge

**Comment by Faolain** [comment]
@erikras / @ecnaidar do the codeclimate issues need to be fixed before merging?

**Comment by kimsy** [comment]
any progress on this pull request?

**Comment by ecnaidar** [comment]
@kimsy
 I was waiting on response from one of the maintainers. Unsuccessfully tho ¯\_(ツ)_/¯

**Comment by Faolain** [comment]
@ecnaidar can you please update the conflicts?

@erikras once he does will this suffice to merge?

**Comment by ecnaidar** [comment]
@Faolain I have resolved conflicts with master. This should be ready to merge. 
I have not idea who we can ping to get this going and I think @erikras gets no notifications from here.
As side note, it was very not fun to run example because they were changed to import script from hosting directly in html.

**Comment by Faolain** [comment]
@gustavohenke can this PR be merged?

**Comment by Faolain** [comment]
@erikras is it possible for this to be merged in?

**Comment by erikras** [comment]
Published in [`v8.2.0`](https://github.com/erikras/redux-form/releases/tag/v8.2.0).

**Pull request merged**
