### PR TITLE
[WIP]Only pass initial values to validate when initialValues present

### LINKED ISSUE #1241: Validate returning undefined as values
Version `5.3.0`

Validate is returning `undefined`, see: 

```js
const validate = (...args) => {
  const errors = {};
  console.log(args);
  // if (!values) return errors;
  //
  // if (!values.email) {
  //   errors.email = 'Required';
  // } else if (!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.email)) {
  //   errors.email = 'Invalid email address';
  // }
  //
  // if (!values.password) {
  //   errors.password = 'Required';
  // }
  //
  // if (fields.includes('passwordConfirmation') && !values.passwordConfirmation) {
  //   errors.passwordConfirmation = 'Required';
  // }
  //
  // if (
  //   fields.includes('passwordConfirmation') &&
  //   values.password &&
  //   values.passwordConfirmation &&
  //   values.password !== values.passwordConfirmation) {
  //   errors.passwordConfirmation = 'Does not match password';
  // }

  return errors;
};

@reduxForm({
  form: 'authentication',
  validate
})
export default class AuthenticationForm extends Component {
  static propTypes = {
    fields: PropTypes.object,
    handleSubmit: PropTypes.func,
    CTA: PropTypes.string.isRequired,
    authError: PropTypes.object,
    submitting: PropTypes.bool
  };

  render() {
    const { fields: { email, password, passwordConfirmation }, handleSubmit, CTA, authError, submitting } = this.props;
    const styles = require('./style.scss');

    return (
      <form className="login-form" onSubmit={(event) => event.preventDefault()}>
        <FormGroup>
          <FormControl {...email} type="email" placeholder="Email" />
          {
            email.touched && email.error &&
            <div className={`text-left ${styles.errorText} text-danger`}>{email.error}</div>
          }
        </FormGroup>
....
```

### PR DESCRIPTION
**Pull request by yesmeck**
~~Should fixes #1241~~

Not ready, do not merge.

### CODE REVIEW

**Comment by yesmeck** [comment]
I recognized that the previous [approach](https://github.com/erikras/redux-form/pull/1061) is  not a good solution, need some time to find a better way to handle this.

**Comment by ooflorent** [comment]
What about reverting the commit? cc @erikras

**Comment by erikras** [comment]
@ooflorent Which commit, specifically?

**Comment by yesmeck** [comment]
This one https://github.com/erikras/redux-form/pull/1061 I think.

**Comment by erikras** [comment]
Rollback published as [`v5.3.1`](https://github.com/erikras/redux-form/releases/tag/v5.3.1).

**Pull request closed without merging**
