### PR TITLE
Fix triggerSubmit/clearSubmit propTypes problems

### LINKED ISSUE #2744: Can we remove `triggerSubmit: func.isRequired` from `src/propTypes.js`?
`triggerSubmit` prop is undocumented ("// didn't find in the docs what is does"), but at the same time, it is marked as required. It is generating false warnings in the developer console since developers don't use this prop (at least I know of no actual, documented usage in the docs and no one mentioned it in the Issues yet.)

We should display no warnings for code developers can't do anything about. Perhaps we should remove `.isRequired` from props that are not required for the form to function properly.

My environment:
Redux-Form 6.5.0, 6.6.0, Chrome (OS X), node 7.7.4

### PR DESCRIPTION
**Pull request by mqklin**
fix https://github.com/erikras/redux-form/pull/2707 problems

Fixes #2744

### CODE REVIEW

**Comment by btimo** [comment]
**triggerSubmit** seems to be a **bool** reporting the state of a form when submitting it.
Multiple proofs available in the source: [](https://github.com/erikras/redux-form/search?utf8=%E2%9C%93&q=triggerSubmit&type=)

**Comment by Empact** [comment]
Oh hey didn't check and made: #2747 you could copy the doc comments from there if you like.

**Comment by mqklin** [comment]
Added your comments.

**Comment by erikras** [comment]
Published in [`v6.6.1`](https://github.com/erikras/redux-form/releases/tag/v6.6.1).

**Pull request merged**
