### PR TITLE
Add missing prop types for Field, FieldArray and Fields components

### PR DESCRIPTION
**Pull request by smashercosmo**

### CODE REVIEW

**Comment by erikras** [comment]
Published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0).

**Comment by fredrik-sogaard** [comment]
@erikras @gustavohenke This PR creates Failed Prop Type warnings when using multiple validators passed as an array (as seen in the docs).

**Comment by fredrik-sogaard** [comment]
Forget it. Just saw this https://github.com/erikras/redux-form/commit/08a377ead23ab34c3116c8e02782b1c292b5ebec

**Comment by floriangosse** [comment]
But it's still missing for `FieldArray`

**Pull request merged**
