### PR TITLE
Create FormName render props component

### PR DESCRIPTION
**Pull request by jedwards1211**
Based upon my suggestion in #4037

### CODE REVIEW

**Comment by danielrob** [comment]
This looks great. Could you just fix those code-climate eslint issues, and we'll await signoff/merge from Erik.

**Comment by jedwards1211** [comment]
Sweet, thanks guys!  At some point I'll get around to releasing my `createStructuredFormSelector` function in a package of its own.

**Comment by jedwards1211** [comment]
@erikras is the goal with the LOC rule to notify you guys when a human code review is needed, and if the length of the function is justified, `eslint-disable` it?

**Comment by jedwards1211** [comment]
Check out https://github.com/jcoreio/redux-form-reselect

**Pull request merged**
