### PR TITLE
BC: Treat undefined and false as NOT equal

### PR DESCRIPTION
**Pull request by erikras**
# ⚠️ BREAKING CHANGE ⚠️

Addresses #3061, #1762, #1774, and #1993.

### CODE REVIEW

**Comment by gustavohenke** [comment]
`v7.0.0` incoming?? 😀

**Comment by erikras** [comment]
Not merging yet until I'm ready to pull the trigger, but yes. This lib needs to be more respectful of semver.

**Comment by helmus** [comment]
@erikras Any idea when this would be released ?

**Comment by erikras** [comment]
Published in [`v7.0.0`](https://github.com/erikras/redux-form/releases/tag/v7.0.0).

**Comment by dwick** [comment]
@erikras shouldn't this also treat `null` and `false` as not equal. upgraded and immediately got bit by that.

**Pull request merged**
