### PR TITLE
Fields validation

### LINKED ISSUE #3492: <Fields /> component field-level validation
### Are you submitting a **bug report** or a **feature request**?
Feature request.

### What is the current behavior?
I have dynamically changing field and I'm using multiple fields ```<Fields />``` component as it perfectly fits my requirements instead of validation.
I'm trying to pass validation array for a current active field or object, where the keys are fields names and values are validation arrays respectively, but nothing happens and redux store is telling me nothing about wrong values.

### What is the expected behavior?
Using of field-level validation in multiple fields ```<Fields />``` component by passing an array of validation functions for current active field or object representing validation for every field.

### What's your environment?
I'm using latest version of redux-form (7.1.0 currently).

### PR DESCRIPTION
**Pull request by EvgeneOskin**
Adding Fields level validation and warning.

`validate` and `warn` props can get an array of objects. Each object will have the fields name and the function(s) to run.

Example:
```jsx
<Fields
  names={['field-1', 'field-2']}
  component={MyComponent}
  validate={[
    {
      name: 'field-1',
      funcs: myRequiredFunction,
    },
    {
      name: 'field-2',
      funcs: myRequiredFunction,
    },
  ]}
  warn={[
    {
      name: 'field-1',
      funcs: myWarnFunction,
    }
  ]}
/>
```

Close #3492

### CODE REVIEW

**Comment by sbogdaniuk** [comment]
@EvgeneOskin any news on this PR ?

**Comment by EvgeneOskin** [comment]
@sbogdaniuk Yes, I've fixed codeclimate checks. All checks pass 😄

**Comment by sbogdaniuk** [comment]
@EvgeneOskin can we go further and use validation and warn for each field

**PropTypes**
```
validate: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.arrayOf(PropTypes.func),
    PropTypes.objectOf(PropTypes.func),
]),
```

**Usage**
```
<Fields
    names={['facebook', 'twitter']}
    component={FormSocials}
    format={plainFormat}
    validate={url}
/>

<Fields
    names={['facebook', 'twitter']}
    component={FormSocials}
    format={plainFormat}
    validate={{
        facebook: url,
        instagram: [required, url],
    }}
/>
```

Use cases
if we pass PropTypes.func or PropTypes.arrayOf(PropTypes.func), we use validation for each field

if PropTypes.objectOf(PropTypes.func), we will take it from object {[name]: func | [func]}

**Comment by EvgeneOskin** [comment]
@sbogdaniuk Thank for your review!

I think, we can go further. I will update this pull request.

**Comment by sbogdaniuk** [comment]
@erikras any thoughts on this?

**Comment by erikras** [comment]
Intriguing idea. Add some tests and docs and we can merge this in.

**Comment by EvgeneOskin** [comment]
Hi @erikras,
I've added some tests and a documentation:smile:

**Comment by erikras** [comment]
The documentation seems wrong (just copied from `Field`); there's no explanation of keyed objects, for example.

**Comment by OlafMerkert** [comment]
We would find this really useful in our project. Is there anything we can do to help move this along?

**Comment by ah-adarlow** [comment]
Does this need to be implemented for immutable Fields as well to maintain parity?

**Comment by EvgeneOskin** [comment]
@erikras I've updated the documentation and fixed merge conflicts.

**Comment by EvgeneOskin** [comment]
@ah-adarlow As far as I understand, it works with immutable fields without additional changes.

**Comment by scottdickerson** [comment]
@ah-adarlow @erikras anything else we could do to help get this one in?

**Comment by ah-adarlow** [comment]
Just FYI, I'm not a maintainer or anything, just an interested party. I've had this code in our codebase for over a month now and it's been working fine. I would love to have an official release instead.

**Comment by erikras** [comment]
Apologies for messing this up, but if you could resubmit this against the new `master`, I would merge it. A lot changed recently. 🙏

**Comment by EvgeneOskin** [comment]
Sure, @erikras. I've resubmitted it – #4301.

**Pull request merged**
