### PR TITLE
add clearAsyncError feature

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
Clear async error by field name. Description: https://github.com/erikras/redux-form/issues/2214

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
https://github.com/erikras/redux-form/issues/2214

**Comment by BrunoQuaresma** [comment]
I don't understand what this means... 😕

**Comment by erikras** [comment]
1. `npm run test:cov`
2. Open `coverage/lcov-report/index.html`
3. Add tests that will run through code in the lines that are not currently covered

Does that help?

**Comment by BrunoQuaresma** [comment]
@erikras updated!

**Comment by Mottoweb** [comment]
I would like to use similar for syncErrors, could you add this or shall i do separate pull request?

**Comment by BrunoQuaresma** [comment]
@Mottoweb I think that you can send it in a separated pull request. 😄

**Comment by erikras** [comment]
Published in [`v6.3.1`](https://github.com/erikras/redux-form/releases/tag/v6.3.1).

**Pull request merged**
