### PR TITLE
Don't use "import * as React" to avoid deprecation warnings

### LINKED ISSUE #3385: React PropTypes and createClass warnings
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
When running jest unit tests touching redux-form related code, those tests log React warnings to the console:

```
console.warn node_modules\react\lib\lowPriorityWarning.js:40
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
    console.warn node_modules\react\lib\lowPriorityWarning.js:40
      Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
```

### What is the expected behavior?
No warnings :)

### What's your environment?
Redux-form 7.0.4
Babel 6.26.0
Jest 21.0.1
Flow 0.49.1
React 15.6.1

### Other information
Related issue: https://github.com/facebook/flow/issues/4673

Culprits: https://github.com/erikras/redux-form/search?l=JavaScript&q=%22+import+%2A+as+React%22+&type=&utf8=%E2%9C%93

### PR DESCRIPTION
**Pull request by gustavohenke**
I never used Flow before, so I have no idea whether this is correct or not 😃 

I just started a trial and error game until the warnings disappeared and no errors were spilled by `npm run test:flow`

Fixes #3385

### CODE REVIEW

**Comment by piuccio** [comment]
is this release already in `7.0.4`?

**Comment by gustavohenke** [comment]
No, it isn't, @piuccio. The problem this PR fixes was introduced in 7.0.4 😐

**Comment by jasonrhodes** [comment]
@erikras if at all possible it would be awesome to cut a tiny release with just this fix ... this is blowing up all test runs with so much noise :/

Thanks for the fix @gustavohenke !

**Comment by jasonrhodes** [comment]
***FWIW anyone else that arrives here, I pinned to 7.0.3 and that solved it for me for now.

**Comment by GuillaumeCisco** [comment]
Should be updated in a new version asap.
I spent one afternoon on this...

**Comment by erikras** [comment]
Published in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).

**Pull request merged**
