### PR TITLE
Update react-redux to use forwardRef syntax

### PR DESCRIPTION
**Pull request by mvanlonden**
WIP DNM

Proposal for react-redux v6 contains breaking changes. This PR is a WIP to address those changes.

https://github.com/reduxjs/react-redux/pull/995

cc @markerikson

### CODE REVIEW

**Comment by erikras** [comment]
I'm ready to merge when the tests pass.

Seems like `package.json` would need to change, no?

**Comment by mvanlonden** [comment]
Took a quick pass but ran into the test failures. This was for compatibility with https://github.com/reduxjs/react-redux/pull/995 but might not matter since the other PR also uses forwarded refs? 

I'm also not very familiar with this codebase and am migrating to a new form library.

**Comment by markerikson** [comment]
PR 1000 was what we finally went with, but they should have ultimately had the same public API.

If I upgrade the peer dep and dev dep to `react-redux@6.0.0-beta.3`, the test failures I'm seeing are stuff like:

```
  ● Fields.immutable › should rerender when sync error is cleared

    expect(jest.fn()).toHaveBeenCalledTimes(1)

    Expected mock function to have been called one time, but it was called two times.

      1400 |       // username input rendered
      1401 |       expect(usernameInput).toHaveBeenCalled()
    > 1402 |       expect(usernameInput).toHaveBeenCalledTimes(1)
           |                             ^
      1403 |
      1404 |       // username field has error
      1405 |       expect(usernameInput.mock.calls[0][0].username.meta.valid).toBe(false)

      at Object.<anonymous> (src/__tests__/Fields.spec.js:1402:29)
```

Lots of stuff like that.

**Comment by markerikson** [comment]
Oh.  Dear.

I just realized that Redux-Form uses legacy React context internally.

That _may_ explain why things appear to be very broken atm.

**Comment by harrythedev** [comment]
I'm switching to formik. 👋

**Comment by erikras** [comment]
Back from vacation. Working on this...

**Comment by cereallarceny** [comment]
@erikras Do we have any rough time estimate on this?

**Comment by erikras** [comment]
Put in about six hours yesterday. Gonna throw some more at it today. Lots of broken tests still.

End of this week, early next week?

**Comment by pogran** [comment]
@cereallarceny , hi.  The problem was fixed?

**Comment by cereallarceny** [comment]
It's not my issue @pogran 😄

**Comment by erikras** [comment]
Published fix in [`v8.0.0`](https://github.com/erikras/redux-form/releases/tag/v8.0.0).

**Comment by Ogala** [comment]
Thanks @erikras. Fix works well so far!

**Pull request closed without merging**
