### PR TITLE
Hoist static fields of the Wrapped Component

### LINKED ISSUE #2230: Your reduxForm hide static react class properties.
The problem is when I use your decorator, it don't copy static properties from original component. Redux decorator for example don't do that, so you have not right architecture.
Here is [screenshots](https://photos.google.com/share/AF1QipOoGmfv8MbfAXc9q0qThjXXIpyU65BkeYW1Ycg0L_aU0y-EyI9OIIxAim0pzst6vA?key=WUlELVFOVkpTYkpEb0VXdXQtSzJ1cVRJRkZUREpB). I think is clear.

### LINKED ISSUE #2626: Hoisting static assets
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

As far as I can tell, `redux-form` is not hoisting static assets. 

### What is the expected behavior?

I would expect it to hoist static assets.

### What's your environment?

```
redux-form: 6.4.3
node: 7.5.0
react-native: 0.41.0
redux: 3.6.0
react-redux: 4.4.6
```

### Other informations

I first thought this was a problem with `react-navigation` and I opened an issue ticket there:

https://github.com/react-community/react-navigation/issues/332#event-961713900

They said that it was an issue with `redux-form`, so I'm posting it here. I'm not sure how to diagnose this problem, but I'm happy to submit a PR if given some guidance.

### PR DESCRIPTION
**Pull request by valerybugakov**
Pretty small fix for #2626 and #2230

Fixes #2626, fixes #2230

### CODE REVIEW

**Comment by valerybugakov** [comment]
@gustavohenke anything else is required for merge?

**Comment by gustavohenke** [comment]
I don't think so. Code changes are handled by @erikras.

**Comment by erikras** [comment]
How the heck did that break? I thought we were always hoisting statics.

**Comment by erikras** [comment]
Published in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).

**Pull request merged**
