### PR TITLE
treats null the same as undefined when setting initial values

### PR DESCRIPTION
**Pull request by yesmeck**
Same as this commit https://github.com/erikras/redux-form/commit/476a4e0517166489a079e263327e65d4220da90b on v6.

### CODE REVIEW

**Comment by ooflorent** [comment]
The following will not work properly on `select` if `multiple` is `true` because `value` has to be defaulted to `[]` otherwise React will raise a warning.

Let's consider the following component:

```js
const SomeSelect = field => (
  <select multiple {...field}>
    <option value="a">A</option>
    <option value="b">B</option>
    <option value="c">C</option>
  </select>
)
```

If `value` is `null` or `undefined` then the component is not managed:

```md
Warning: `value` prop on `select` should not be null. Consider using the empty 
string to clear the component or `undefined` for uncontrolled components.
```

If `value` is `""` (empty string) then `PropTypes` are not met:

```md
Warning: The `value` prop supplied to <select> must be an array if `multiple` is true.
```

**Comment by ooflorent** [comment]
Why did you create `isNil` instead of using the same trick as Erik did on v6?

**Comment by yesmeck** [comment]
> Why did you create isNil instead of using the same trick as Erik did on v6?
 
Just don't want repeat `eslint-disable-line eqeqeq`

**Comment by yesmeck** [comment]
I have not looked into v6, do you known how v6 handle default value for multiple select?

**Comment by yesmeck** [comment]
> The following will not work properly on select if multiple is true because value has to be defaulted to [] otherwise React will raise a warning.

IMHO, if people want to use multiple select, they should given a initial array value to the field. This behaviour is same like v6 dose.

**Pull request closed without merging**
