### PR TITLE
added missing export for getFormSyncErrors

### PR DESCRIPTION
**Pull request by anthonychung14**
One-line fix to enable getFormSyncSelector. Needed it to make a feature

### CODE REVIEW

**Comment by bmv437** [comment]
this fixes #1977

**Comment by gipsy-king** [comment]
should be added to `src/immutable.js` too, I think.

**Comment by 92bondstreet** [comment]
Hi @erikras ,

Do you think to publish shortly a patch ?

Thanks !

**Comment by erikras** [comment]
Published in [`v6.2.0`](https://github.com/erikras/redux-form/releases/tag/v6.2.0).

**Pull request merged**
