### PR TITLE
Added normalize prop to Field

### PR DESCRIPTION
**Pull request by erikras**
This accomplishes _most_ of what the `v5` [`reducer.normalize()`](http://redux-form.com/5.2.5/#/api/reducer/normalize) API was providing.

### CODE REVIEW

**Comment by erikras** [comment]
@ooflorent Opinions on this?

**Comment by ooflorent** [comment]
I always disliked how normalization works until this patch. 
Moving this to `Field` was the right move. 

👍  on removing getters! I think you forgot to update the [Instance API documentation](https://github.com/erikras/redux-form/blob/v6/docs/api/Field.md#instance-api).

**Comment by erikras** [comment]
Great.

>  I think you forgot to update the Instance API documentation.

I don't think so. I only removed getters on `ConnectedField`, not on `Field`, which is what the docs address.

**Comment by ooflorent** [comment]
Oh my bad.

**Comment by erikras** [comment]
Published as [`v6.0.0-rc.1`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.1).

**Pull request merged**
