### PR TITLE
Add missing propTypes

### PR DESCRIPTION
**Pull request by jdreesen**
This adds some missing propTypes to the ones that get passed to your decorated form component.

### CODE REVIEW

**Comment by erikras** [comment]
Thanks. These are little details that can get overlooked as new features are added. 👍

**Comment by mqklin** [comment]
@erikras how can I use it? 6.5.0 is the latest release

**Comment by gustavohenke** [comment]
It isn't released yet.

**Comment by erikras** [comment]
Published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0).

**Comment by mqklin** [comment]
Thank you!

**Pull request merged**
