### PR TITLE
fix erikras/redux-form#3489

### PR DESCRIPTION
**Pull request by Defenderbass**

### CODE REVIEW

**Comment by Defenderbass** [comment]
fix erikras/redux-form#3489

**Comment by cristian-sima** [comment]
Any chance to get this change in a release very soon. It breaks the code... :(

**Comment by erikras** [comment]
Published in [`v7.2.1`](https://github.com/erikras/redux-form/releases/tag/v7.2.1).

**Comment by cristian-sima** [comment]
fixed. thanks

**Pull request merged**
