### PR TITLE
Fix ConnectedField to accept values that isn't React SyntheticEvent (#3446)

### PR DESCRIPTION
**Pull request by antonbasic**
Fixes [#3446](https://github.com/erikras/redux-form/issues/3446)

### CODE REVIEW

**Comment by jamesmillerburgess** [comment]
This issue has been a pain for us to work around. Thanks for making this PR!

**Comment by NihalSh** [comment]
@antonbasic 
Thanks for making the PR. This issue was blocking our migration to a newer version of redux-form. I am anxiously waiting for the merge to go through.

**Comment by rajagopal4890** [comment]
@antonbasic That's great! Struggling with this for a while. during our migration. hope this gets merged soon.

**Comment by rajagopal4890** [comment]
Team, is this change accepted and a merge is planned?

**Comment by yale** [comment]
Thank you @antonbasic for this fix! We've hit this same issue. Are there any plans to merge this soon?

**Pull request merged**
