### PR TITLE
Avoided unnecessary call to sync validation

### LINKED ISSUE #2583: Validation is triggered twice on form init
### Are you submitting a **bug report** or a **feature request**?
Bug ?

### What is the current / expected behavior?
In `Synchronous Validation Example` validate function is trigged twice, before form is mounted and after it's rendered.

Since nothing was changed in the form, why do we need to trigger it twice, is it by design?

### What's your environment?
Redux form 6.5.0

### PR DESCRIPTION
**Pull request by erikras**
Fixes #2583.

### CODE REVIEW

**Comment by erikras** [comment]
Published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0).

**Comment by KatFishSnake** [comment]
@erikras can you please look into @stream7 referenced issue its breaking for multiple people

**Comment by dizlexik** [comment]
I'll second that, @KatFishSnake.

@erikras, issue #2971 is a critical failure of the reset function and @stream7 seems to have tracked it down to this PR. I'm not in any position right now to rollback/build/test but when you get a chance could you please take a look?

**Comment by yohnstoppable** [comment]
Anyone have a workaround to fix this? Still doesn't work in 7.0.3

**Pull request merged**
