### PR TITLE
Potential fix for #468

### PR DESCRIPTION
**Pull request by flaub**
Potential fix for #468 

It forces the user to specify the shape of the value being passed into `addField`. But at least it allows me to use redux-form on my project!

### CODE REVIEW

**Comment by nathanmarks** [comment]
Hey Flaub,

I haven't taken a look at the `redux-form` code related to this issue yet, so a quick Q for you:

Is there no way to use the field config passed to the `reduxForm` HoC?

**Comment by flaub** [comment]
That's option 2 I listed as a potential solution to issue #468 

I'm not familiar with the codebase enough to get the `ADD_ARRAY_VALUE` action to have access to the original `fields` setup by the HoC. I do think this is a better solution. Do you have any ideas how to accomplish this?

**Comment by nathanmarks** [comment]
I'll have to dig in and take a look. Will do if I get the time later -- using your patch temporarily so I can get some work done today ;)

**Comment by flaub** [comment]
@nathanmarks I think I've got it figured out as you suggested, checkout the updated PR.

**Comment by nathanmarks** [comment]
@flaub Just set it up, will do a day of developing with it tomorrow. So far so good.

`

**Comment by flaub** [comment]
Feel free to use `https://github.com/flaub/redux-form/tarball/dist` for your package.json dependency until this PR gets merged.

**Comment by nathanmarks** [comment]
@flaub Thanks!

**Comment by erikras** [comment]
This is great @flaub! This was not a trivial problem. :+1: :beers: 

I've been on vacation, so sorry it took so long to get back to you.

**Comment by nathanmarks** [comment]
@flaub Yeah, great job flaub!

**Comment by flaub** [comment]
Wonderful, I'm glad there were lots of tests so I couldn't screw up too much!

Great library BTW!

**Pull request merged**
