### PR TITLE
Use separate blur method to set visited status

### PR DESCRIPTION
**Pull request by whodidthis**
https://github.com/erikras/react-redux-universal-hot-example/issues/101

Adding a separate blur action for marking `visited` to make validation a bit more friendly

### CODE REVIEW

**Comment by erikras** [comment]
I considered this, and even began implementing it, but later decided against it. It's a matter of taste, I guess. I prefer the immediate reaction of the validation. 

And, unless I'm mistaken, they can't really coexist that well. Either you mark visited on change or not.

Let me think about it a bit more. And see if you can think of an elegant way for onlyMarkVisitedOnBlur to be an option.

**Comment by whodidthis** [comment]
I think it could make sense to add a `changed` tree in addition to `visited`.

So in react-redux-universal-hot-example's case recreating the immediate behavior would be
```js
emailError && (emailVisited || emailChanged) && <div className="text-danger">{emailError}</div>
```

AngularJS has good support for really pinpointing how to display validation (taken from https://docs.angularjs.org/guide/forms):
> - ng-valid: the model is valid
- ng-invalid: the model is invalid
- ng-valid-[key]: for each valid key added by $setValidity
- ng-invalid-[key]: for each invalid key added by $setValidity
- ng-pristine: the control hasn't been interacted with yet
- ng-dirty: the control has been interacted with
- ng-touched: the control has been blurred
- ng-untouched: the control hasn't been blurred
- ng-pending: any $asyncValidators are unfulfilled

**Comment by erikras** [comment]
How can something "change" without being "visited"?

I think you might be onto something with the idea of copying those flags from angular.

**Comment by whodidthis** [comment]
Yeah, might be better to use similar flags with angular. I at least saw a couple of react form libs using `pristine/dirty`.

I could update pull request changing `visited` to `touched` and instead of `changed` adding `dirty`, if you want.

**Comment by dzannotti** [comment]
is there a way to have validation called only on submit or pre-submit or something like that?

**Comment by erikras** [comment]
Many of the ideas discussed here just got implemented in the v0.0.7 release. @whodidthis, I'd appreciate your feedback. This discussion was a big influence.

**Comment by whodidthis** [comment]
Awesome :sunglasses:

**Comment by ericclemmons** [comment]
Wandered on this thread from Reactiflux & I wanted to point out that, in the case of autocomplete, you'll definitely have lots of change events that the user may never have touched (or even seen, if it's hidden).

**Comment by erikras** [comment]
Having thought about it for only 30 seconds after reading your comment, @ericclemmons, I would think that autocomplete would be handled by its own component, which would use its own reducer, and only call `handleChange` when a value was selected.

**Comment by ericclemmons** [comment]
@erikras It's...quite a bit more complex than that :)  Unfortunately, the browser's autocomplete doesn't have an event to listen to.

Similar to the "autosuggest" on phones, all you'll get is an `onChange` fired all over the place :)

Enjoy! Muwhahahahahahahahaha

**Comment by whodidthis** [comment]
Probably just means don't disable submit buttons because of any validation errors and remember to `touchAll` on submit and you should be good to go? Or at least to the extent easily possible.

https://github.com/erikras/redux-form#-touchall--function

**Pull request closed without merging**
