### PR TITLE
Fix initialising a nested array value with an object.

### PR DESCRIPTION
**Pull request by latentflip**
Fixes: #377

Hope this makes sense. Passes all existing tests, and the new one I added.

I know you're looking at reworking the init stuff anyway as per the comments in #377 but it'd be great to get a fix in for this for what we're doing :)

nb: also fixed the title of a test that looks like it's wrong.

<3

### CODE REVIEW

**Comment by Strajk** [comment]
:+1:

**Comment by erikras** [comment]
Thank you for this, but there were a couple of other birds that needed killing with this stone.

The issue this PR fixes should be fixed in [`v4.0.0`](https://github.com/erikras/redux-form/releases/tag/v4.0.0). Come and get it!

**Comment by latentflip** [comment]
Sweet, we're going to try it out right now!

**Comment by Strajk** [comment]
Everything is awesome! Thanks so much for your work!

**Comment by Strajk** [comment]
Actually, haven't found a way how to accomplish this in 4.0.0 :/ @erikras @latentflip 

dev flight deals from 50 16 250km 2015-12-15 19-54-55

**Comment by erikras** [comment]
Oh, I'm sorry. I misunderstood your issue.

**Comment by Strajk** [comment]
No worries, still a great update! Can you please reconsider this PR?

**Comment by erikras** [comment]
The `initializeState()` function is precisely what changed in the `v4.0` update, so this fix requires some extra effort.

**Comment by lukekarrys** [comment]
I added another commit to this over in https://github.com/erikras/redux-form/pull/425 which I think fixes the issue now in v4.

**Pull request closed without merging**
