### PR TITLE
Allow removal of the whole form object from the reducer

### PR DESCRIPTION
**Pull request by bbenezech**
for proper memory management with apps that generate a significant amount of dynamic forms.

### CODE REVIEW

**Comment by erikras** [comment]
Excellent PR, @bbenezech!

**Comment by erikras** [comment]
Even added the docs to the readme! :+1: :+1:

**Comment by bbenezech** [comment]
Thanks. The PR is pretty much all copy pasta. I couldn't remove the hash key while keeping the super-duper reducer generator pattern you used. If you have any idea...

**Comment by erikras** [comment]
Can you be more specific?

**Comment by erikras** [comment]
Oh, I see what you mean.

**Comment by bbenezech** [comment]
Yes. I just replaced the Object with undefined, I did not remove the key.

On a separated topic, I missed createAll.js

Not sure what it does and why my patch worked without it.

I'm writing a commit.

**Comment by erikras** [comment]
I just noticed that you missed `createAll` as I was reviewing.

**Comment by bbenezech** [comment]
annnnnd native.js... Really sorry, strike two.

**Pull request merged**
