### PR TITLE
Passthrough the initialValues prop to the enhanced component.

### LINKED ISSUE #1570: [v6rc5] initialValues are not propagated
```
@connect(mapStateToProps)
@reduxForm(...)
export default class extends Component {
  render() {
    console.log(this.props.initialValues) <-- undefined
    ...
  }
}

function mapStateToProps(state){
  return { initialValues: { ...} }
}
```
However in v6rc4 worked fine

### PR DESCRIPTION
**Pull request by ruiaraujo**
Fixes #1570.

### CODE REVIEW

**Comment by erikras** [comment]
With docs update and everything! ❤️!

In my `v6` issue fixing rampage this morning, I was subconsciously skipping  #1570 because I didn't understand just how simple it was. Thanks for this.

**Comment by ruiaraujo** [comment]
Thanks for redux-form and for merging!

**Comment by erikras** [comment]
Published in [`v6.0.1`](https://github.com/erikras/redux-form/releases/tag/v6.0.1).

**Comment by oomathias** [comment]
I'm using redux-form 6.5.0, and on first render initialValues prop is undefined.
I should say, that initialValues are populated from the state.
Even inside `render() or componentDidMount()` `this.props.initialValues === undefined`, but the form is correctly initialised with the values.
If I trigger another render, values are correctly populated.

I need to access these initialValues on first render, to generate some `<options />`

Should I open another issue?

**Pull request merged**
