### PR TITLE
add a jsnext:main so we can distribute ES2015 modules

### PR DESCRIPTION
**Pull request by Whoaa512**
See https://github.com/rollup/rollup#can-i-distribute-my-package-as-an-es6-module

### CODE REVIEW

**Comment by erikras** [comment]
Should the webpack build also generate a separate module that is transpiled to es6, not es5?

**Comment by erikras** [comment]
Oh, I see. You're pointing it at *src*! Interesting.

**Comment by taion** [comment]
This is incorrect, BTW: https://github.com/rollup/rollup/wiki/jsnext:main

`jsnext:main` should be a transpiled build with everything but the ES modules transform.

See e.g. how Redux and React Router do it.

**Comment by swernerx** [comment]
That @taion is saying is right. The current `jsnext:main` entry breaks webpack 2 with babel as one typically do not transpile content from the node_modules folder.

**Comment by swernerx** [comment]
See also: https://github.com/reactjs/redux/issues/1042

**Comment by taion** [comment]
Ahh, this was actually fixed on the beta releases.

**Comment by erikras** [comment]
@taion, so is this something I need to look into or not?

**Comment by taion** [comment]
@erikras 

Probably not. It was fixed in the `v6` branch in https://github.com/erikras/redux-form/commit/56a3af112b0cc2c51cbb4752a9bc7d41e57e5a2d.

I was going off a comment elsewhere and didn't realize that your development code was not on the `master` branch.

**Pull request merged**
