### PR TITLE
Replaced usages of for...of construct for stupid IE

### PR DESCRIPTION
**Pull request by erikras**
As suggested by @jerrysu on #2720.

### CODE REVIEW

**Comment by jerrysu** [comment]
Thank you! Looking forward to the new release!

**Comment by jptconiconde** [comment]
Awesome, thanks guys :)

**Comment by gustavohenke** [comment]
@jerrysu, this was published in [`v6.6.0`](https://github.com/erikras/redux-form/releases/tag/v6.6.0)!

**Comment by pgom** [comment]
Just a suggestion on this. We can set the [loose](https://babeljs.io/docs/plugins/transform-es2015-for-of/#optionsloose) flag to `true` on the `transform-es2015-for-of` plugin.

**Pull request merged**
