### PR TITLE
Add getFormError selector

### PR DESCRIPTION
**Pull request by faizrr**
Should close https://github.com/erikras/redux-form/issues/3463

I didn't change `getFormSyncErrors`, `getFormAsyncErrors`, `getFormSubmitErrors` methods, because we can set `_error` prop not only via SubmissionError. And we can't determine how `_error` prop was set. The simplest way - is to add one more selector.

### CODE REVIEW

**Comment by Noitidart** [comment]
Thanks @faizrr! For my learnng, Im kind of new to redux-from, how else can I set _error?

**Comment by faizrr** [comment]
@Noitidart via sync validation, for example (https://redux-form.com/7.0.4/examples/syncvalidation/)

**Comment by Noitidart** [comment]
Ooh, thanks @faizrr

**Comment by erikras** [comment]
Awesome. Update the docs and I'll merge.

**Comment by erikras** [comment]
Nevermind, I'll add the docs. 😄

**Comment by Noitidart** [comment]
Super cool thanks folks!!

**Comment by erikras** [comment]
Published in [`v7.1.0`](https://github.com/erikras/redux-form/releases/tag/v7.1.0).

**Pull request merged**
