### PR TITLE
Pass correct function params

### PR DESCRIPTION
**Pull request by jansons**

### CODE REVIEW

**Comment by erikras** [comment]
Ha! Thanks. Already did that in my local version. Thanks for your help. Closing, tho.

**Comment by jansons** [comment]
Hi, Erik!
Just wanted to let you know that this problem still exists in alpha.7 release (and quick look shows that there could be similar problem in FieldArray as well).

**Comment by erikras** [comment]
What the?? How on earth is this building or running, then?

**Comment by erikras** [comment]
OH! Because it's correct in the constructor! Got it.

**Comment by erikras** [comment]
I was actually about to write a test to hit the other `createConnectedField()` call because the test coverage report told me that it was untested. Hooray for test coverage! (and observant helpful folks like you 😄 )

**Comment by jansons** [comment]
👍

**Comment by erikras** [comment]
Fix published as [`v6.0.0-alpha.8`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.8).

**Pull request closed without merging**
