### PR TITLE
Stop unregistering fields if `destroyOnUnmount` is false & always pass `keepDirtyOnReinitialize`as second argument to initialize action

### PR DESCRIPTION
**Pull request by ncphillips**

### CODE REVIEW

**Comment by bbenezech** [comment]
Just tried it, `keepDirtyOnReinitialize` finally works for real. Thanks @ncphillips

**Comment by erikras** [comment]
Great PR, @ncphillips.

Thanks for the confirmation, @bbenezech. That helps me a lot.

**Comment by ncphillips** [comment]
Thank you guys @erikras and @bbenezech. This is a great library, and this was the one serious problem I've had with it so far.

**Comment by erikras** [comment]
Published in [`v6.2.1`](https://github.com/erikras/redux-form/releases/tag/v6.2.1).

**Pull request merged**
