### PR TITLE
v6 — Fix navigator

### PR DESCRIPTION
**Pull request by ooflorent**
See #971 
See https://github.com/tmpvar/jsdom/commit/306805ad7dd8435b868ed95ae699116346201d06

### CODE REVIEW

**Comment by erikras** [comment]
I think I put that there for code coverage reasons, because the last branch of [this line](https://github.com/erikras/redux-form/blob/v6/src/isReactNative.js#L5) was never reached.

Run a `npm run test:cov` and look at `coverage/lcov-report/index.html`.

See if you can figure out a way to get it to 100%.

**Comment by ooflorent** [comment]
Coverage is 100% now without doing anything. Maybe previous versions of `jsdom` don't define `product` causing the coverage issue.

**Comment by erikras** [comment]
Alrighty, then!

**Comment by erikras** [comment]
```
=============================== Coverage summary ===============================
Statements   : 100% ( 4442/4442 ), 118 ignored
Branches     : 99.9% ( 1019/1020 ), 179 ignored
Functions    : 100% ( 959/959 ), 11 ignored
Lines        : 100% ( 2956/2956 )
================================================================================
```
Branches is not 100%.

**Comment by ooflorent** [comment]
Sorry but they are when I ran the coverage on my machine.

screen shot 2016-05-16 at 15 16 39

**Comment by erikras** [comment]
Upgrading JSDom to 9.1.0 fixed it.

**Pull request merged**
