### PR TITLE
Hotfix: Revert all UNSAFE_ lifecycle methods

### LINKED ISSUE #4069: [v7.4.0] initialValues not working
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
initialValues prop is not working on initial mount after update to 7.4.0

### Sandbox Link
I've modified the **Initialize from state** demo just to show the issue. I've just change:
```
 state => ({
    initialValues: data
 }),
```
to get values directly from the variable instead after clicking the button.

https://codesandbox.io/s/ox3p66023q

As you can see the fields are empty. If you change the redux-form version to 7.3.0 it works.

### What's your environment?
redux-form 7.4.0

### PR DESCRIPTION
**Pull request by danielrob**
The addition of the `UNSAFE_` lifecycle methods broke React 15 compatibility. Those methods are not intended for libraries still supporting React 15. 

The only way to remove the React 16.4+ `StrictMode` warnings about `cWM`, `cWRP`, and `cWU` in a React 15 compatible way is to migrate these methods to the new lifecycle methods and use `react-lifecycles-compat` for backwards compatibility. The `UNSAFE_` methods were to support application authors with a known target version of React (16.3+) from having to migrate every component before upgrading. Unfortunately we can't do that trick. 

#### Additional Testing
Since the automated tests are all run against React 16, I've confirmed this locally by building my fork, and copying the `lib` folder to `node_modules/redux-form` of a download of [this sandbox](https://codesandbox.io/s/r0o9q33lmp) which is against 15.6, and confirming that the initialValues (as per #4069) are now showing. That's the only test I've run.  

#### Should fix
#4069, #4070, #4072

### CODE REVIEW

**Comment by erikras** [comment]
This is because I'm an idiot and didn't use the polyfill properly. I made the same mistake in another library.

**Comment by erikras** [comment]
I'll fix this immediately.

**Comment by erikras** [comment]
Published fix in [`v4.7.1`](https://github.com/erikras/redux-form/releases/tag/v7.4.1).

**Comment by danielrob** [comment]
Sorry, I should have looked more deeply into the polyfill, they didn't mention on the front page it also supported the `UNSAFE_` methods... I should have dug deeper! Thanks Erik!

**Comment by danielrob** [comment]
Wait... it doesn't...

**Comment by erikras** [comment]
Misunderstanding on my part, apparently. 🤦‍♂️

**Comment by erikras** [comment]
Published in [`v7.4.2`](https://github.com/erikras/redux-form/releases/tag/v7.4.2).

**Pull request merged**
