### PR TITLE
event with value key shouldnt be special case

### LINKED ISSUE #1355: Value shouldn't look for a prop within the object
Im having issues creating complex value types that instead of holding strings hold objects/bools/arrays or any other thing.
But this really puzzled me https://github.com/erikras/redux-form/blob/v6/src/events/getValue.js#L41
I had to read the source to figure out what was going on.
Turns out calling `onChange` with an object that has a `value` key will use the value of that key as the new value, which is very cryptic.
Please remove this

### PR DESCRIPTION
**Pull request by eloytoro**
Closes #1355

### CODE REVIEW

**Comment by eloytoro** [comment]
hmm tests passed dont know why it reports that it didnt

**Comment by erikras** [comment]
This looks good. I will evaluate when I get back from vacation next week.

**Comment by erikras** [comment]
FYI: Your test problem was a linting error with a stray semicolon.

**Comment by erikras** [comment]
Published in [`v6.0.0-rc.4`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.4).

**Pull request merged**
