### PR TITLE
Pass props through Field and FieldArray using props prop

### PR DESCRIPTION
**Pull request by vslinko**
ref https://github.com/erikras/redux-form/issues/1066

### CODE REVIEW

**Comment by erikras** [comment]
Great PR. 👍  Can you do [the docs](https://github.com/erikras/redux-form/tree/v6/docs/api), too?

**Comment by vslinko** [comment]
@erikras updated

**Comment by ooflorent** [comment]
It looks really good! Maybe you could add a note about _why_ this prop was introduced.

**Comment by erikras** [comment]
Yes, what @ooflorent said. ☝️

**Comment by vslinko** [comment]
I don't know what to add as the reason.

**Comment by erikras** [comment]
Published as [`6.0.0-alpha-15`](https://github.com/erikras/redux-form/releases/tag/v6.0.0-alpha.15).

**Comment by rluiten** [comment]
I think there may be a small issue here, if its a bug or not I could not say.

I was creating a helper component to output BooleanRadioField with label and error display area.

I had already discovered that I must pass in the property "type" to `Field` so that the logic in processProps() can create the checked property for me.

The `type` field works in either the Field properties or in the 'props' property.

For setting the value of a radio input I have tried both
 ```html
<Field name="option1" component="input" props={{type="radio", value=false}} />
```
and
 ```html
<Field name="option1" component="input" props={{type="radio", value="false"}} />
```
Neither set the value attribute on the input element.

Only this works for actually setting the radio button attribute named "value".
```html
<Field name="option1" component="input" props={{type="radio"}} value={false} />
```

**Comment by CarsonF** [comment]
Is this still needed? I know there are a lot of changes for how props are passed in RC4. I haven't needed it for my TypeScript definition. And IMO it just makes things more confusing.

**Comment by rluiten** [comment]
In my opinion it is not needed, i was just using at one point.

**Comment by erikras** [comment]
📟 @vslinko

**Comment by vslinko** [comment]
I'm not using v6 right now, so I don't have solid opinion on that.

**Comment by erikras** [comment]
Well, @CarsonF is the current `v6` typescript expert, so I'm inclined to go with him.

**Comment by CarsonF** [comment]
@vslinko [Here's](https://github.com/erikras/redux-form/pull/1318#issuecomment-236655775) the example I gave @rluiten. The concept can be applied to any component. The example creates a class so it's reusable but really only the first two lines inside `render()` that are needed if you are doing a one-off.

**Pull request merged**
