### PR TITLE
A new prop: onSubmitFail

### PR DESCRIPTION
**Pull request by puradox**
This pull request is partly stemming from the conversation over at #776.

The way that we currently are submitting forms is great! Except for one thing... we don't know whether or not the submission failed. There is a current (quite *hacky*) way of checking this through the use of the `returnRejectedSubmitPromise` flag. Using this flag is quite tricky and cumbersome. It causes what some might call a programmer's headache (#488, #256, #291, #616). It even called a noble programmer, @pcgilday, to resolve some confusion with [his comment](https://github.com/erikras/redux-form/issues/616#issuecomment-209105697) which acted as a guide for many.

I believe that handling a failed submission should be more programmer-friendly, in a way that is also React oriented. So all of this is a major cause for a new prop: `onSubmitFail`.

The new prop `onSubmitFail` will be passed to your form upon initialization, and will act like one would think. It gets called when the form gets submitted and failed validation. Simple enough. No ES6 promises. No more headaches. Just a callback. And maybe even a smile :smile:

Callback syntax: `onSubmitFail(errors: object | undefined)`

The `errors` parameter will contain the errors returned from *synchronous* validation. This parameter will be an `object` if a synchronous validation fails in the form `{ field: error, ... }`. However, it could also be `undefined` if an asynchronous validation fails.

Edit: Added new `errors` parameter

### CODE REVIEW

**Comment by puradox** [comment]
As a worthy mention, I only intend for this to be a temporary solution to the problem. We getting closer to the big rewrite, `v6.0`. :tada:

**Comment by erikras** [comment]
Nice work, @puradox. :+1:

**Comment by erikras** [comment]
Someone was also asking for an `onSubmitSuccess` callback. While you're in there and clearly understand the tests and `handleSubmit()`, can you add that, too?

**Comment by puradox** [comment]
@erikras Thanks! I assumed that the existing `onSubmit` callback was equivalent to an `onSubmitSuccess` callback, am I wrong? I'll double check in the code.

**Comment by erikras** [comment]
Both `onSubmitFailed` and `onSubmitSuccess` _could_ be done with the existing promise API, but it's about convenience.

**Comment by puradox** [comment]
@erikras If I were to implement an `onSubmitSuccess` callback, there would be some a bit of extra redundancy. Are you sure you want me to implement this?

In my own code, I use `onSubmit` **without** the `returnRejectedSubmitPromise` flag to check if the submission was successful (it only fires if the submit was successful). Then I use `onSubmitFail` to check if the submission was erroneous.

This whole proposal was to eliminate the need for the `returnRejectedSubmitPromise` flag and promise rejection altogether, while maintaining backwards compatibility.

However, I do see your point in creating a more explicit callback that does exactly what it says. I agree that this would completely eliminate a lot of the existing confusion. I'll get working on it.

**Comment by erikras** [comment]
No, I'm not 100% sure, but, at the risk of increasing API surface area, I do plan on implementing both in v6. You are more than welcome to say no. This PR still stands as an improvement.

**Comment by puradox** [comment]
@erikras What's the status on this PR? Can we get it merged into `master`?

**Comment by erikras** [comment]
I'll document and publish soon (tomorrow). 👍

**Comment by puradox** [comment]
@erikras Thanks man! I'm very excited to see this go out. I appreciate all that you've done for the React / Redux community :smile: If you need any help with the new rewrite, you can always mention me. I'll be glad to help out.

**Comment by erikras** [comment]
Published as [`v5.1.0`](https://github.com/erikras/redux-form/releases/tag/v5.1.0). Thanks again.

You've shown that you know your way around the library, so if I need someone for the rewrite, you're on the shortlist. 😉

**Comment by CodyReichert** [comment]
Hi, I'm looking for the documentation for `onSubmitSuccess` and `onSubmitFailure`, but can't find it here: http://redux-form.com/5.2.3/#/api/props?_k=j59cbr

I see it's pretty know, so understandable that it's not up there yet. Is this something you're intentionally holding off on, or can someone (me or anyone else) provide a PR adding these to the v5 docs?

**Comment by erikras** [comment]
@CodyReichert Ha, no, those are props that you pass to the decorated form, not that `redux-form` provides to your wrapped component. So their docs are [here](http://redux-form.com/5.2.3/#/api/reduxForm).

I suppose they _could_ be, but that was not the intention when `onSubmitSuccess` and `onSubmitFailure` were proposed and implemented.

**Comment by CodyReichert** [comment]
@erikras - heh, I realized that _right_ after I submitted the comment. Thank you!

**Comment by brennancheung** [comment]
How can I get access to React `refs` from inside of `onSubmitFail`?  I'm trying to do something like:

```
class LoginPage extends React.Component {
  render () {
    ...
    <input ref="password" />
    ...
}
export default reduxForm(
  {
    form: 'login',
    fields: [ 'username', 'password' ],
    validate,
    onSubmitFail: (errors) => {
      React.findDOMNode(this.refs.password).focus()
    }
  }
)(LoginPage)
```

**Comment by Strajk** [comment]
Hi @brennancheung , have you found a way to do that?

**Comment by brennancheung** [comment]
@Strajk I went with `document.getElementById('password').focus()` for now.  I know it's not the best way to do it and it won't work for server side rendering but I couldn't find any other way.  I still think it is an issue not being about to have access to the component within the `onSubmitFail` handler though.

**Comment by puradox** [comment]
@brennancheung @Strajk You are going to want to utilize the prop version of `onSubmitFail`. 
> IMPORTANT: All of these configuration options may be passed into reduxForm() at "design time" **or passed in as props** to your component at runtime. ([source](http://redux-form.com/5.2.3/#/api/reduxForm?_k=v6g2l8))

Your refactored React Component would then look **something** like this (I haven't tested this):
```javascript
@reduxForm({
  form: 'login',
  fields: [ 'username', 'password' ],
  validate
})
class LoginPage extends Component {
  focusPasswordField() {
    this.refs.password.focus();
  }
  render() {
    ...
    <input ref="password" />
    ...
  }
}

class App extends Component {
  handleSubmitFail(errors) {
    this.refs.login.focusPasswordField();
  }
  render() {
    ...
    <LoginPage ref="login" onSubmitFail={this.handleSubmitFail} />
    ...
  }
}
```

**Comment by brennancheung** [comment]
@puradox, `this.refs.login.focusPasswordField` does not exist in your example.  `this.refs.login.refs` exists but it doesn't contain the actual refs (it's an empty object).  None of the methods I define in `LoginPage` seem to be visible from `this.refs.login`.

**Comment by puradox** [comment]
@brennancheung Ah yes, I forgot that the class is being wrapped by Redux-Form. I doubt that we'd be able to access the underlying component (`LoginPage` in our case) since `createHigherOrderComponent` doesn't keep a `ref` to it. That means that we have to think of another way...

**Comment by puradox** [comment]
@brennancheung Instead, another approach would be one that is completely unrelated to `onSubmitFail`, is to provide your own `handleSubmit` method. I tested this time :smile: 

```javascript
function validate(values) {
  const errors = {};
  if (!values.password || values.password !== 'secret') {
    errors.password = 'Invalid';
  }
  return errors;
}

@reduxForm({
  form: 'login',
  fields: ['username', 'password'],
  validate
})
class LoginPage extends Component {

  handleSubmit = (event) => {
    const { fields, handleSubmit } = this.props;

    handleSubmit(event);

    if (fields.password.error) {
      this.refs.password.focus();
    }
  }

  render() {
    const { fields: { username, password } } = this.props;
    return (
      <form onSubmit={this.handleSubmit}>
        <input placeholder="Password" type="password" ref="password" {...password} />
        <input placeholder="Username" {...username} />
        <button type="submit">Submit</button>
        {password.touched && password.error && <div>{password.error}</div>}
      </form>
    );
  }
}

class App extends Component {
  handleSubmit = values => console.log(values)
  handleSubmitFail = errors => console.log(errors)
  render() {
    return (
      <LoginPage onSubmit={this.handleSubmit} onSubmitFail={this.handleSubmitFail} />
    );
  }
}
```

**Pull request merged**
