### PR TITLE
Add support for redux 4.x

### PR DESCRIPTION
**Pull request by ApacheEx**
Redux 4 is out: https://github.com/reactjs/redux/releases/tag/v4.0.0

I didn't notice any breaking changes. 💯
This is small and clear PR, hope I didn't miss anything.

### CODE REVIEW

**Comment by prescottprue** [comment]
Was this supposed to have been published to NPM? When installing `7.3.0` I see that the package file still points to just `^3.0.0`.

**Comment by gustavohenke** [comment]
@prescottprue v7.3.0 was released nearly 1.5 months before this PR was merged, so no.

**Comment by prescottprue** [comment]
@gustavohenke Any idea of when it will be published?

**Comment by burtek** [comment]
@erikras @gustavohenke It's been merged over a week ago. There are plenty of people waiting for this to be pushed to npm. Any idea how soon that's gonna happen?

**Comment by erikras** [comment]
🎉 Released in [`v7.4.0`](https://github.com/erikras/redux-form/releases/tag/v7.4.0). 🎉

**Pull request merged**
