### PR TITLE
blur should do anything if it does not target the active field

### PR DESCRIPTION
**Pull request by ooflorent**
This PR adds a test to demonstrate the issue exposed in https://github.com/erikras/redux-form/issues/1001#issuecomment-220128834.
It also fixes the issue #1001.

**DO NOT MERGE if this is the expected behavior!**
**DO NOT MERGE if we consider this bug as a _feature_ because it lives for too long!**

### CODE REVIEW

**Comment by erikras** [comment]
This is definitely the right way to handle this. 👍

**Comment by erikras** [comment]
Can you implement this in `v6`, too, if it's not already?

**Comment by erikras** [comment]
`< .01%` code coverage increase! 🎉 😄

**Comment by ooflorent** [comment]
> Can you implement this in v6, too, if it's not already?

I'll do it tomorrow!

**Comment by erikras** [comment]
Released as [`v5.2.4`](https://github.com/erikras/redux-form/releases/tag/v5.2.4).

**Pull request merged**
