### PR TITLE
Added @@ infront of action names

### PR DESCRIPTION
**Pull request by liamhubers**
Following the convention of adding @@ in front of action names

### CODE REVIEW

**Comment by DanielRuf** [comment]
@liamhubers can you point me to the convention? At least I find nothing about it http://redux.js.org/docs/basics/Actions.html

**Comment by liamhubers** [comment]
I had a look and can't find it written anywhere, but people seem to be doing it anyway:
https://github.com/reactjs/redux/blob/master/src/createStore.js#L11
https://github.com/reactjs/react-router-redux/blob/a304bda820ba57f68961035eff1950e618047b81/src/reducer.js#L5

It's convenient me because I need to filter out all third-party redux actions

**Comment by DanielRuf** [comment]
Ah ok. Yes,s aw it when I printed the triggered actions and then saw the double `@`. Good to know (y)

**Comment by erikras** [comment]
This _could_ be a breaking change if anyone was dumb enough (or just n00b enough) to listen for one of these actions via an `action.type === 'stringvalue'`.

**Comment by erikras** [comment]
Published in [`v6.2.1`](https://github.com/erikras/redux-form/releases/tag/v6.2.1).

**Pull request merged**
