### PR TITLE
Migrate to Jest using jest-codemods 

### PR DESCRIPTION
**Pull request by skovhus**
This PR migrates the codebase from Mocha/Expect@1 (deprecated) to Jest.

I've been dogfooding my own tool https://github.com/skovhus/jest-codemods that handles automatic migrations to Jest.

I've made additional changes to jest-codemods in order to make it as clever as possible, so only a few manual steps are required. The hard part has been all the custom extensions of expect. I've learned a lot from seeing expect@1 being used in the wild, and I hope it will benefit users of jest-codemods. : )

### TODO
- [x] get rid of custom expect extensions (expect, predicate, immutable)
- [x] ensure we are up to date with master
- [x] ensure number of asserts matches old codebase (1624 pass here, same as on master)

### CODE REVIEW

**Comment by skovhus** [comment]
@erikras they should be ready for review and merge if you are happy with the changes.

Thanks for letting me using this repo for improving / dogfooding jest-codemods. : )

**Comment by skovhus** [comment]
@erikras let me know if there is anything you would like me to change / fix.

**Comment by erikras** [comment]
This is a hectic week, as I'm preparing a talk. Will revisit in October.

**Comment by skovhus** [comment]
@erikras 👍 . 

I've just rebased with master.

**Comment by erikras** [comment]
Brilliant work, mate!

Unfortunately, I'm clueless with git, and could not figure out how to push additional merges and fixes to this PR branch. As such, we now have a [skovhus-jest-codemods](https://github.com/erikras/redux-form/tree/skovhus-jest-codemods) branch, which _should_ preserve your contributions.

Unfortunately, there's a failing test that makes no sense to me (I had to upgrade to `immutable@4.0.0-rc.3`):

```
 FAIL  src/structure/immutable/__tests__/deepEqual.spec.js
  ● structure.immutable.deepEqual › should work with plain objects inside Immutable.Maps

    TypeError: Invalid keyPath: expected Ordered Collection or Array: a.b.g

      at coerceKeyPath (node_modules/immutable/dist/immutable.js:1932:9)
      at Map.updateIn (node_modules/immutable/dist/immutable.js:2045:7)
      at Map.setIn (node_modules/immutable/dist/immutable.js:2005:17)
      at Object.<anonymous> (src/structure/immutable/__tests__/deepEqual.spec.js:119:5)
          at Promise (<anonymous>)
          at <anonymous>
```

So I guess I'm closing this, with the intention of merging _that_ branch asap whenever I can figure out this problem. If anyone reading this has any clue how to fix that, I'd love a PR (to that branch) to do so.

**Comment by skovhus** [comment]
So no tests failed on this branch. Wondering why you branched out. I could easily pull in master if you wanted me to.

**Comment by skovhus** [comment]
Seems that all the dependency upgrading caused the immutable error.

Let me know why this was done, and I can help you out. : )

**Comment by erikras** [comment]
Well, the problem was that _master_ was not passing `flow check`, so I went to fix it, and it required upgrading `immutable`, which cascaded on to..... you know how it goes.

**Comment by erikras** [comment]
Yes, the tests were working on this branch. 💯 thanks for that.

**Comment by skovhus** [comment]
So the change seems unrelated. Would be nice to keep separate then...

That master is not passing `flow check` seems like there is an issue with the checks running on PRs.

**Comment by skovhus** [comment]
Might be an idea to fix the flow errors on master before merging this.

**Comment by erikras** [comment]
Yes, for sure. The current problem is 0% your fault. But I've branched your work into a new branch that I hope to reunite with `master` asap.

**Comment by skovhus** [comment]
> But I've branched your work into a new branch that I hope to reunite with master asap.

I just don't understand the approach. It makes it rather hard to reason about fixing Flow AND upgrading Jest at the same time. ; )

`yarn run test:flow` works for me on master. What error do you get?

**Comment by erikras** [comment]
You make a good point.

**Comment by skovhus** [comment]
Made a PR that makes it clear what target are run (and runs flow):
https://github.com/erikras/redux-form/pull/3469

**Pull request merged**
