### PR TITLE
Wrong validation of calculating max length

### PR DESCRIPTION
**Pull request by burakdirin**
Wrong validation of calculating max length on example

### CODE REVIEW

**Comment by erikras** [comment]
No, the code is correct.

**Comment by burakdirin** [comment]
this code is correct ? :) 

`const minValue = min => value =>value && value < min ? 'Must be at least' + min : undefined`

check out please -> https://jsfiddle.net/0pgb1prk/

**Comment by gustavohenke** [comment]
@burakdirin, the deal with this example is to validate that a number is less than `min`. It's not related to string length.

**Comment by burakdirin** [comment]
Now I understand much more clearly, sorry :)

**Pull request closed without merging**
