### PR TITLE
Only wrap FormSection in a div if necessary

### PR DESCRIPTION
**Pull request by SimenB**
I don't want extra `div`s in my DOM 😄

### CODE REVIEW

**Comment by erikras** [comment]
Nice one. 💥 those semicolons and I'll merge it.

**Comment by SimenB** [comment]
@erikras Updated 😄

**Comment by SimenB** [comment]
I'm thinking it might be better to do `React.Children.only` to force consumer to only pass a single element. Can be a dumb `div` if they want, or do something more, like add classes, animate it etc. That's a breaking change though

**Comment by erikras** [comment]
Published in [`v6.3.1`](https://github.com/erikras/redux-form/releases/tag/v6.3.1).

**Comment by SimenB** [comment]
My last comment was solved beautifully with #2329

**Pull request merged**
