### PR TITLE
Make sure syncErrors is a Map

### LINKED ISSUE #3036: syncErrors does not have a .get() method
Using immutableJS (and redux-form/immutable), I'm getting this error on 6.6.0 and 6.7.0, but 6.5.0 works fine:

```
Invalid keyPath: Value at ["syncErrors"] does not have a .get() method: [object Object]
```

Here's what I believe is the relevant piece of my validation function:

```
import validations from 'utils/validations'
import Big from 'big.js'

const validate = newRecord => values => {
  const errors = {
    song: {
      attributes: {}
    },
  }

  const song = values.toJS().song || {
    attributes: {}
  }

  /*** Song ***/
  errors.song.attributes.title = validations.required(song.attributes && song.attributes.title)
  errors.song.attributes.key = validations.required(song.attributes && song.attributes.key)

  /*** SongAudioFiles ***/
  errors.song.song_audio_files = { _error: validations.minArrayLength(1)(song.song_audio_files, "At least one audio file is required") }
  if(!errors.song.song_audio_files._error) {
    let primaryFileExists = false
    song.song_audio_files.forEach(song_audio_file => {
      if(song_audio_file.attributes.primary == 1) {
        primaryFileExists = true
      }
    })
    errors.song.song_audio_files = { _error: primaryFileExists ? undefined : "Must have one audio file marked as primary" }
  }

  // ... more stuff ...

  return errors
}

export default validate
```

### PR DESCRIPTION
**Pull request by delold**
Fixes #3036 

For those, who use Immutable v4.0.0-rc2

### CODE REVIEW

**Comment by delold** [comment]
Will do a proper pull request

**Comment by gustavohenke** [comment]
There's no need to close this one. Just keep improving it.

**Comment by delold** [comment]
this PR might create more problems though, as now the sync errors are immutable, which might break some apps

**Comment by erikras** [comment]
No, `syncErrors`, even for immutable users, are supposed to be in a javascript object. That is intentional.

**Comment by delold** [comment]
Already fixed in PR #3219, closing

**Pull request closed without merging**
