### PR TITLE
Ensure initial values are present on first render

### LINKED ISSUE #621: Form values not initialized from initialValues until 2nd render cycle
We have been struggling w/ this for a while now and following some of the related issues. I'm not sure if our problem is directly related to these others or not (using release `4.1.6`):

- https://github.com/erikras/redux-form/issues/176
- https://github.com/erikras/redux-form/issues/578

To summarize, we are finding that values are not being initialized until the second render cycle for our reduxForm-ed components. Example being that none of the following properties would be initialized until the first call of `componentWillReceiveProps` (i.e. the 2nd render):

- `props.fields.someField.value`
- `props.values.someField`

Although, the following properties **are** initialized (even for the 1st render cycle) according to `initialValues`

- `props.fields.someField.defaultValue`
- `props.fields.someField.initialValue`
- etc...

My question would be, is what I've described above the _expected_ behavior from `redux-form`? This causes issues for us where children component who depend on valid props being passed down to them receive `undefined` on the 1st render cycle and we can not rely on the "values" being reliably initialized.

We have resorted to something similar to

```js
render() {
  if (typeof values.someField === 'undefined') {
    return null;
  }

  // ...
}
```

but then we can not rely on componentDidMount, etc...

I will make an effort to circle back and try and clarify this issue. I just want to get this out there for possible discussion. Any feedback/advice is much appreciated!

---

Here is some mostly-valid code below to illustrate the issue we have been experiencing

```js
const SomeForm = React.createClass({

  componentWillMount() {
    const {values} = this.props;
    if (typeof values.someString === 'undefined') {
      // All values = undefined
      // props.fields.someString.defaultValue is set as expected
      // props.fields.someString.initialValue is set as expected
      debugger;
    } else {
      debugger;
    }
  },

  componentDidMount() {
    const {values} = this.props;
    if (typeof values.someString === 'undefined') {
      // All values = undefined
      // props.fields.someString.defaultValue is set as expected
      // props.fields.someString.initialValue is set as expected
      debugger;
    } else {
      debugger;
    }
  },

  componentWillReceiveProps(newProps) {
    const {values} = newProps;
    if (typeof values.someString === 'undefined') {
      debugger;
    } else {
      // Values initialized on 1st call (2nd render)
      debugger;
    }
  },

  render() {
    const {
      fields: {someString, someArray, someObject},
    } = this.props;

    return (
      <div>
        <ComponentUsesSomeString
          value={someString.value}
          onChange={someString.onChange}
        />
        <ComponentUsesSomeArray
          value={someArray.value}
          onChange={someArray.onChange}
        />
        <ComponentUsesSomeObject
          value={someObject.value}
          onChange={someObject.onChange}
        />
      </div>
    )
  }

});

const ReduxFormedSomeForm = reduxForm(
  {name: 'SomeForm', fields: ['someString', 'someArray', 'someObject']},
  (state) => {
    return {
      initialValues: {
        someString: 'Some String',
        someArray: ['some', 'array'],
        someObject: {a: 'some', b: 'object'},
      },
    };
  }
)(SomeForm);

const App = React.createClass({
  render() {
    return (
      <div>
        <ReduxFormedSomeForm />
      </div>
    )
  }
})
```

### PR DESCRIPTION
**Pull request by yesmeck**
Attempt to fix #621

### CODE REVIEW

**Comment by erikras** [comment]
👍 @yesmeck

**Comment by erikras** [comment]
Published as [`v5.2.5`](https://github.com/erikras/redux-form/releases/tag/v5.2.5).

**Comment by cpsubrian** [comment]
👍  FWIW fixed my issue with checksum fail on server-side-rendered forms.

**Comment by mpolichette** [comment]
@yesmeck You're my hero! thanks!

**Pull request merged**
