### PR TITLE
Added 'resetSection' action

### PR DESCRIPTION
**Pull request by fantua**
I'll add tests and docs after reviewing and approval.

Issue: [#2239](https://github.com/erikras/redux-form/issues/2239#issuecomment-272634628)

### CODE REVIEW

**Comment by fantua** [comment]
cc @erikras

**Comment by erikras** [comment]
Looks fine to me. 👍

**Comment by fantua** [comment]
@erikras looks like I'm done 😃 

But seems I'm too late for `v7.2.2` release.

**Comment by erikras** [comment]
Published in [`v7.3.0`](https://github.com/erikras/redux-form/releases/tag/v7.3.0).

**Pull request merged**
