### PR TITLE
fixes Can't find variable: File error

### PR DESCRIPTION
**Pull request by vitalis**
introduced in react native by #886

### CODE REVIEW

**Comment by antoinerousseau** [comment]
Beautiful, thanks!
Just tried it and works for me (React Native 0.24.1 / Android Genymotion)

**Comment by erikras** [comment]
Thanks, @vitalis, and thanks @antoinerousseau for confirming.

**Comment by kristian-puccio** [comment]
Can we get a release of this pushed?

**Comment by erikras** [comment]
@kristian-puccio Thanks for the nudge. [`v5.2.4`](https://github.com/erikras/redux-form/releases/tag/v5.2.4)

**Comment by kristian-puccio** [comment]
thanks mate :)

**Pull request merged**
